### ISSUE TITLE
Implementação da Pool de Threads

### ISSUE THREAD

**Issue by GuilhermeCassFerreira** [GuilhermeCassFerreira/INE-5645-Programa-o-Paralela-e-Distribu-da#1]
## Contexto

A central de controle deve operar sobre várias unidades de processamento, as quais são threads em uma pool de threads.

## Descrição

Deve ser implementada uma pool de threads para ser utilizada pela central de controle.

**Comment by padiilha** [comment]
Vamos adaptar essa issue para apenas tratar da criação da _pool de threads_ e o uso dela será feito na issue #2
