### ISSUE TITLE
Delegar a alteração do nível de atividade para uma unidade de processamento

### ISSUE THREAD

**Issue by GuilhermeCassFerreira** [GuilhermeCassFerreira/INE-5645-Programa-o-Paralela-e-Distribu-da#2]
## Descrição

A central de controle deve delegar a alteração do nível de atividade do atuador para uma unidade de processamento, a qual é uma thread na pool de threads

## Definition of Ready (DoR)
- [x] #1

**Comment by padiilha** [comment]
Essa implementação já está parcialmente feita, porém falta delegar para a atleração ser realizada por uma unidade de processamento (thread) da _pool de threads_
