### ISSUE TITLE
Sincronização e Comunicação Adequadas:

### ISSUE THREAD

**Issue by GuilhermeCassFerreira** [GuilhermeCassFerreira/INE-5645-Programa-o-Paralela-e-Distribu-da#3]
É necessário garantir a sincronização adequada entre as threads para evitar condições de corrida e garantir a consistência dos dados compartilhados.
    Implementar mecanismos de comunicação entre threads para passar informações sobre alterações nos atuadores e envio de mensagens ao painel do veículo.

**Comment by padiilha** [comment]
Em geral, creio que isso já está sendo feito, só falta o bloqueio da impressão na tela
