### ISSUE TITLE
Tempo de Manutenção do Nível de Atividade:

### ISSUE THREAD

**Issue by GuilhermeCassFerreira** [GuilhermeCassFerreira/INE-5645-Programa-o-Paralela-e-Distribu-da#4]
As unidades de processamento devem ser responsáveis por manter o nível de atividade dos atuadores no valor desejado por pelo menos 2 segundos, conforme especificado no enunciado.
    Após a alteração do nível de atividade, deve haver um atraso correspondente antes que o próximo valor seja processado.

**Comment by padiilha** [comment]
Isso já está sendo feito com `sleep(2 + rand() % 2);`
