### ISSUE TITLE
Adaptar código para uso de fork-join

### ISSUE THREAD

**Issue by GuilhermeCassFerreira** [GuilhermeCassFerreira/INE-5645-Programa-o-Paralela-e-Distribu-da#6]
## Contexto
Foi verificado o código com o professor e foi levantado o ponto em que não havia o comportamento de _join_ após a execução das subtarefas do atuador.

## Descrição
Deve ser realizado o _join_ das threads (ou processos) para então ser impressa a mensagem de falha, caso esta seja verdadeira (1)

**Comment by padiilha** [comment]
Acho que talvez isso não seja necessário, pois na descrição do trabalho está escrito:

_Para cada tarefa recebida pela unidade de processamento, são duas subtarefas (divisão), que podem ser executadas de forma independente (fork)_
